#define hel int
#define flyde float
#define hvis if
#define ellers else
#define imens while
#define forhver for
#define returner return
#define knap switch
#define mulighed case
#define oedlaeg break
#define standard default
#define hoved main
#define tomrum void

#define afbryd abort
#define absolutvaerdi abs
#define arkuskosinus acos
#define tidsangivelse asctime
#define tidsangivelse_r asctime_r
#define arkussinus asin
#define paastand assert
#define arkustangens atan
#define arkustangens2 atan2
#define vedafslutning atexit
#define strengtilfloat atof
#define strengtilinteger atoi
#define strengtillang atol
#define binaersoegning bsearch
#define bytetilwctegn btowc

#define calloc calloc
#define katluk catclose
#define katfaa catgets
#define kataaben catopen
#define afrundingopad ceil
#define rydfejl clearerr
#define ur clock
#define cos cosinus
#define cosinushyperbolicus cosh
#define tidsformat ctime
#define tidsformat64 ctime64
#define tidsformat_r ctime_r
#define tidsformat64_r ctime64_r
#define tidsforskel difftime
#define tidsforskel64 difftime64
#define division div
#define fejlfunktion erf
#define komplementaerfejlfunktion erfc
#define afslutning exit
#define eksponential exp
#define absolutvaerdi fabs
#define lukfil fclose
#define aabnfilskriver fdopen
#define filslut feof
#define filfejl ferror
#define toem fflush
#define henttegn fgetc
#define hentposition fgetpos
#define hentstreng fgets

#define hentwstreng fgetws

#define filnummer fileno
#define afrundingnedad floor
#define modulo fmod
#define aabnfil fopen
#define skrivtilfil fprintf
#define skrivtegn fputc
#define skrivstreng fputs
#define skrivwctegn fputwc

#define skrivwstreng fputws

#define laesfil fread
#define fri free
#define aabnomfil freopen
#define opsplitfloat frexp
#define laesfrafil fscanf
#define springtil fseek
#define saetposition fsetpos
#define fortel ftell
#define filbredde fwide

#define fwprintf fwprintf

#define skrivtilfil fwrite
#define fwscanf fwscanf

#define gamma gamma
#define henttegn getc
#define henttegn getchar
#define hentmiljoe getenv
#define hentstreng gets
#define hentwctegn getwc

#define hentwchar getwchar
#define lokaltid gmtime
#define lokaltid64 gmtime64
#define lokaltid_r gmtime_r
#define lokaltid64_r gmtime64_r
#define hypot hypotenuselaengde
#define eralfanumerisk isalnum
#define eralfabetisk isalpha
#define erascii isascii
#define ertomrumstegn isblank
#define erkontroltegn iscntrl
#define ertal isdigit
#define ergrafisk isgraph
#define ersmaabogstav islower
#define erprintbar isprint
#define ertegnsaettende ispunct
#define ertomrum isspace
#define erstorbogstav isupper
#define erwalfanumerisk iswalnum
#define erwalfabetisk iswalpha
#define erwaltomrumstegn iswblank
#define erwalkontroltegn iswcntrl
#define erwctype iswctype
#define erwaltal iswdigit
#define erwalgrafisk iswgraph
#define erwalsmaabogstav iswlower
#define erwalprintbar iswprint
#define erwaltegnsaettende iswpunct
#define erwaltomrum iswspace
#define erwalstorbogstav iswupper
#define erwalhexatal iswxdigit
#define erhexatal isxdigit
#define j0 j0
#define j1 j1
#define jn jn
#define absolutvaerdi labs
#define eksponentielstoerrelse ldexp
#define division ldiv
#define lokalespecifikation localeconv
#define lokalformat localtime
#define lokalformat64 localtime64
#define lokalformat_r localtime_r
#define lokalformat64_r localtime64_r
#define log logaritme
#define logaritme10 log10
#define langsprung longjmp
#define tildelhukommelse malloc
#define multibyteslaengde mblen
#define multibytespositionslaengde mbrlen
#define multibytestilwctegn mbrtowc
#define mbsinit mbsinit
#define multibytestilwcs mbsrtowcs
#define multibytestilwcs mbstowcs
#define multibytestilwctegn mbtowc
#define findbyte memchr
#define sammenlignhukommelse memcmp
#define kopierhukommelse memcpy
#define flythukommelse memmove
#define fyldhukommelse memset
#define dannetid mktime
#define dannetid64 mktime64
#define frakomma modf
#define naesteefter nextafter
#define naesteefterl nextafterl
#define naestetil nexttoward
#define naestetill nexttowardl
#define nl_langinfo nl_langinfo
#define fejlmeddelelse perror
#define potens pow
#define skriv printf
#define skrivtegn putc
#define skrivtegn putchar
#define saetmiljoe putenv
#define skrivstreng puts
#define skrivwctegn putwc

#define skrivwchar putwchar
#define qsort qsort
#define quantexpd32 quantexpd32
#define quantexpd64 quantexpd64
#define quantexpd128 quantexpd128
#define quantized32 quantized32
#define quantized64 quantized64
#define quantized128 quantized128
#define sammequantumd32 samequantumd32
#define sammequantumd64 samequantumd64
#define sammequantumd128 samequantumd128
#define haeve raise
#define tilfaeldigtal rand
#define rand_r rand_r
#define omfordelhukommelse realloc
#define regulerudtrykssammensaetning regcomp
#define regulerudtryksfejl regerror
#define regulerudtryksudfoerelse regexec
#define regulerudtryksfrigoerelse regfree
#define fjern remove
#define omdoeb rename
#define nulstil rewind
#define laes scanf
#define saetbuffert setbuf
#define saetspringmaerke setjmp
#define saetlokal setlocale
#define saetbuffert setvbuf
#define signal signal
#define sinus sin
#define sinushyperbolicus sinh
#define skrivtilstreng snprintf
#define skrivtilstreng sprintf
#define kvadratroed sqrt
#define srand srand
#define laesfrastring sscanf
#define sammenlignstrengignorecase strcasecmp
#define sammensaetstreng strcat
#define findtegn strchr
#define sammenlignstreng strcmp
#define sammenlignstrengkulturelt strcoll
#define kopierstreng strcpy
#define findstrengtegn strcspn
#define fejlmeddelelse strerror
#define formatrundt strfmon
#define formattid strftime
#define strenglaengde strlen
#define sammenlignstrengignorecase strncasecmp
#define sammensaetstreng strncat
#define sammenlignstreng strncmp
#define kopierstreng strncpy
#define findstrengtegn strpbrk
#define tidsformat strptime
#define findtegnomvendt strrchr
#define strxfrm strxfrm
#define swprintf swprintf
#define swscanf swscanf
#define system system
#define tangent tan
#define tangenthyperbolicus tanh
#define tid time
#define tid64 time64
#define midlertidigfil tmpfile
#define midlertidignavn tmpnam
#define tilascii toascii
#define smaabogstav tolower
#define storbogstav toupper
#define towctrans towctrans
#define smaabogstavw towlower
#define storbogstavw towupper
#define opsla ungetc
#define opslawctegn ungetwc

#define va_arg va_arg
#define va_copy va_copy
#define va_end va_end
#define va_start va_start
#define vfprintf vfprintf
#define vfscanf vfscanf
#define vfwprintf vfwprintf

#define vfwscanf vfwscanf

#define vprintf vprintf
#define vscanf vscanf
#define vsprintf vsprintf
#define vsnprintf vsnprintf
#define vsscanf vsscanf
#define vswprintf vswprintf

#define vswscanf vswscanf

#define vwprintf vwprintf

#define vwscanf vwscanf
#define wcrtomb wcrtomb
#define wcssammensaet wcscat
#define wcsfindtegn wcschr
#define wcscompare wcscmp
#define wcssammenlign wcscoll
#define wcsskopi wcscpy
#define wcsfindtegnstreng wcscspn
#define wcsformattid wcsftime
#define wcsstrelaengde wcslen
#define wcslokalopsaetning wcslocaleconv
#define wcsnsammensaet wcsncat
#define wcsnsammenlign wcsncmp
#define wcsnkopi wcsncpy
#define wcsfindtegnstreng wcspbrk
#define wcsformattid wcsptime
#define wcsfindtegnomvendt wcsrchr
#define wcsrtombs wcsrtombs
#define wcsspn wcsspn
#define wcsfinddelstreng wcsstr
#define wcsstredouble wcstod
#define wcsstredouble32 wcstod32
#define wcsstredouble64 wcstod64
#define wcsstredouble128 wcstod128
#define wcsstrefloat wcstof
#define wcsstrtok wcstok
#define wcsstrelong wcstol
#define wcsstredoublel wcstold
#define wcsmbstil wcstombs
#define wcsstreulong wcstoul
#define wcsxfrm wcsxfrm
#define wctob wctob
#define wctomb wctomb
#define wctrans wctrans
#define wctype wctype
#define wcwidth wcwidth
#define wmemfindbyte wmemchr
#define wmemsammenlign wmemcmp
#define wmemkopi wmemcpy
#define wmemflyt wmemmove
#define wmemfyld wmemset
#define wprintf wprintf
#define wscanf wscanf
#define y0 y0
#define y1 y1
#define yn yn
